# Generated by Django 2.1.7 on 2019-05-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiceupprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceupprofile',
            name='district',
            field=models.CharField(default=113, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voiceupprofile',
            name='isPolitician',
            field=models.BooleanField(default=False),
        ),
    ]
